project:
  type: website
  output-dir: docs

website:
  title: "SPEI – Cogotí y Ramadas"
  navbar:
    left:
      # Asegúrate que estas carpetas existan (si tus archivos están en la raíz, borra 'pagina_quarto/')
      - href: index.qmd
        text: Inicio
      - href: spei.qmd
        text: Análisis SPEI

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css