project:
  type: website
  output-dir: docs

website:
  title: "SPEI – Cogotí y Ramadas"
  navbar:
    left:
      # RUTAS CORREGIDAS: Apuntan directamente al archivo en la raíz
      - href: index.qmd
        text: Inicio
      - href: spei.qmd
        text: Análisis SPEI


format:
  html:
    theme: cosmo
    toc: true
    css: styles.css